#!/bin/bash
set -eu
cd "$(dirname "$0")"

case "${1:-run}" in
	run | lint) ;;
	install)
		echo "Installing pre-commit"
		(cd .git/hooks && ln -sf ../../pre-commit .)
		exit;;
	uninstall)
		echo "Uninstalling pre-commit"
		rm -f .git/hooks/pre-commit
		exit;;
	*)
		echo "Invalid option: $*"
		echo "Supported options: install, uninstall"
		exit 1;;
esac

# Check directory
[ -d .git ] || cd ../..

# Run checks
for precommit in custom/*/pre-commit
do
	echo "Project > $precommit"
	(cd "$(dirname "$precommit")" && ./pre-commit "${1:-}")
done

echo "Project > All good to commit"
