#!/bin/bash
set -eu
# Check directory
cd "$(dirname "$0")"
[[ "$0" != *.git/hooks/* ]] || cd ../..

pre_commit() {
	for precommit in addons/*/pre-commit
	do
		echo "Project > $precommit"
		(cd "$(dirname "$precommit")" && ./pre-commit "${1:-run}")
	done
	echo "Project > Done"
}

# Commands
case "${1:-run}" in
	install)
		echo "Installing pre-commit"
		cd .git/hooks
		ln -sf ../../pre-commit pre-commit
		;;
	uninstall)
		echo "Uninstalling pre-commit"
		rm -f .git/hooks/pre-commit
		;;
	-*)
		echo "Invalid argument: $*"
		echo "Supported options: lint, install, uninstall"
		;;
	*)
		pre_commit "${1:-run}"
		;;
esac
