#!/usr/bin/env python3

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
import odoo
import sys

if __name__ == "__main__":
    # TODO rewrite bash script
    # TODO replace argv
    sys.argv = ['test']
    odoo.cli.main()
