#!/bin/bash
set -eu
cd "$(dirname "$0")"

case "${1:-run}" in
	run | lint) ;;
	format)
		black .
		isort .
		exit 0;;
	install)
		echo "Installing pre-commit"
		(cd .git/hooks && ln -sf ../../pre-commit .)
		exit;;
	uninstall)
		echo "Uninstalling pre-commit"
		rm -f .git/hooks/pre-commit
		exit;;
	-*)
		echo "Invalid option: $*"
		echo "Supported options: install, uninstall"
		exit 1;;
	*)
		echo "Unsupported command: $*"
		exit 0;;
esac

# Run checks
flake8
black --check .
isort --check-only .

if [ "${1:-}" == 'lint' ]
then
	# only during linting (tools which are quite slow)
	# xmllint for files
	if type xmllint &> /dev/null
	then
		find -name '*.xml' -type f | xargs xmllint -noout
	else
		echo "xmllint not installed"
		exit 1
	fi
	# Skipping: import-error (odoo not available in github actions)
	pylint --errors-only -e odoolint -d import-error \
		$(find -name '__manifest__.py' -exec dirname '{}' ';')
fi

echo "All good to commit"
