#!/bin/bash
set -eu
# Check directory
cd "$(dirname "$0")"
[[ "$0" != *.git/hooks/* ]] || cd ../..

pre_commit() {
	flake8
	black --check .
	isort --check-only .
}

format() {
	black .
	isort .
}

lint() {
	pre_commit

	# xmllint for files
	if type xmllint &> /dev/null
	then
		find -name '*.xml' -type f | xargs xmllint -noout
	else
		echo "xmllint not installed"
		exit 1
	fi
	# Skipping: import-error (odoo not available in github actions)
	pylint -d import-error \
		$(find -name '__manifest__.py' -exec dirname '{}' ';' | sort)
}

# Commands
case "${1:-run}" in
	run)
		pre_commit
		echo "All good to commit"
		;;
	lint)
		lint;;
	format)
		format;;
	install)
		echo "Installing pre-commit"
		cd .git/hooks
		ln -sf ../../pre-commit pre-commit
		;;
	uninstall)
		echo "Uninstalling pre-commit"
		rm -f .git/hooks/pre-commit
		;;
	*)
		echo "Invalid argument: $*"
		echo "Supported options: lint, install, uninstall"
esac
