#!/bin/bash
set -eu
# Check directory
cd "$(dirname "$0")"
[[ "$0" != *.git/hooks/* ]] || cd ../..

pre_commit() {
	flake8
	black --check .
	isort --check-only .
}

lint_text() {
	if find -name '*.xml' -type f -print0 | xargs -0 \
		grep --files-with-matches --max-count 5 --line-number -P '^\t'
	then
		echo '... should be indented with spaces'
		return 1
	fi
	find -name '*.xml' -type f -print0 | xargs --no-run-if-empty -0 -n1 -P5 \
		python3 -c 'import xml.etree.ElementTree as ET; import sys; ET.parse(sys.argv[1])'
}

format() {
	black .
	isort .
}

lint() {
	pre_commit
	lint_text
	# Skipping: import-error (odoo not available in github actions)
	pylint -d import-error \
		$(find -name '__manifest__.py' -exec dirname '{}' ';' | sort)
}

# Commands
case "${1:-run}" in
	run)
		pre_commit
		echo "All good to commit"
		;;
	lint)
		lint;;
	format)
		format;;
	install)
		echo "Installing pre-commit"
		cd .git/hooks
		ln -sf ../../pre-commit pre-commit
		;;
	uninstall)
		echo "Uninstalling pre-commit"
		rm -f .git/hooks/pre-commit
		;;
	*)
		echo "Invalid argument: $*"
		echo "Supported options: lint, install, uninstall"
esac
